config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'sessions/new'
  get 'sessions/signup'
  root 'application#home'
  
  get '/', to: 'application#home'
  get '/application/add_player'
  post '/application/add_player' => 'application#add_to_roster'
  
  get '/login' => 'sessions#new'
  get '/signup' => 'sessions#signup'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
    belongs_to :team
    has_one :user, through: :team
end

app/models/player_datum.rb
class PlayerDatum < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
    has_many :players
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :teams
    has_many :players, through: :teams
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def home
        isLoggedIn?
        if User.where(name: session[:name]).first
            @players = User.where(name: session[:name]).first.players
        else
            @players = []
        end
    end

    def add_player
        @team = User.where(name: session[:name])
        isLoggedIn?
    end

    def add_to_roster
        Player.create()
        render :add_player
    end

    private

    def isLoggedIn?
        if session[:name]
        else
            redirect_to '/login'
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        session[:name] = params[:name]
        if session[:name] != nil
            if session[:name].strip.length > 0
                redirect_to '/'
            end
        else
        redirect_to '/login'
        end
    end

    def destroy
        session.delete :name
        redirect_to '/login'
    end

    def signup
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/application/add_player.html.erb
<h1><%= 'This is the add page' %></h1><br>

<% ranked_players = PlayerDatum.order(rank: :asc) %>

<style>

th {
    background: #336B87;
}

tr {
    background: #f3f3f3;
}

tr:nth-child(even) {
    background: #E6F5FF;
}

.container {
    min-width: 400px;
    border-collapse: collapse;
    font-size: 1.3em;
    text-align: left;
    border-radius: 10px 10px 0 0;
    overflow: hidden;
}

.container thead tr{
    background-color: lightblue;
     color: white;
    font-weight: bold;
    text-align: left;
}

.container th, .container td {
    padding: 12px 15px;
}

.container tbody tr {
    border-bottom: 1px solid lightgrey;
}

.container tbody tr:last-of-type {
    border-bottom: 2px solid lightgrey;
}

.add_submit {
    height: 50px;
    border: 1px solid #f3f3f3;
    background-color: #ffffff;
    border-radius: 5px 5px 5px 5px;
    position: relative;
}
 


</style>

<% i = 0 %>
    <table style="width:90%; margin-right: auto; margin-left: auto;" class="container">
        <thead>
            <tr>
                <th>#</th>
                <th>Rank</th>
                <th>Name</th>
                <th>Position</th>
                <th>Yards</th>
                <th>Touchdowns</th>
                <th>Comb</th>
                <th>FGM</th>
                <th>FG Att</th>
                <th>A-M</th>
                <th>Add To Roster</th>
            </tr>
        </thead>
        <tbody>
        <%while i < 100%>
            <tr>
                <td><%= i+1 %></td>       
                <td class="sever"><%= ranked_players[i].rank %></td>       
                <td><%= ranked_players[i].name %></td>
                <td><%= ranked_players[i].position %></td>
                <td><%= ranked_players[i].yards %></td>
                <td><%= ranked_players[i].touchdowns %></td>           
                <td><%= ranked_players[i].comb %></td>
                <td><%= ranked_players[i].fg_m %></td>
                <td><%= ranked_players[i].fg_att %></td> 
                <td><%= ranked_players[i].a_m %></td>
                <td>
                    <%=form_for :player do |f|%>
                        <input type="hidden" name= "id" value=<%=ranked_players[i].id%>>
                        <%=f.submit%>
                    <%end%>
                </td>
            </tr>
            <% i += 1%>
        <%end%>
        </tbody>
    </table>

app/views/application/home.html.erb
<h1>Hi, <%= session[:name] %>.</h1>
<%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>
  <input type=submit value='logout'>
<% end %>
<br>
<br>
<% @players.each do |player|  %>
    <%= player.name%>
    <br>
<% end %>

<%= link_to "Add Player to Roster", application_add_player_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FantasyDraftFootball</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>